apiVersion: v1
kind: Service
metadata:
  namespace: cvmfs
  labels:
    k8s-app: frontier-squid
  name: frontier-squid
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    k8s-app: frontier-squid
  type: ClusterIP
