apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-nodeplugin
  namespace: cvmfs
  labels: 
    k8s-app: cvmfs-nodeplugin
spec:
  selector:
    matchLabels:
      k8s-app: cvmfs-nodeplugin
  template:
    metadata: 
      labels:
        k8s-app: cvmfs-nodeplugin
    spec:
      serviceAccount: cvmfs-nodeplugin
      initContainers:
      - name: create-mountpoint
        image: busybox
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        command: ['sh', '-c', "mkdir -p /cvmfs-root/cvmfs-k8s"]
        resources:
           limits:
             memory: 0.5Gi
             cpu: 1
           requests:
             memory: 0.2Gi
             cpu: 0.01
        volumeMounts:
        - mountPath: /cvmfs-root
          name:  cvmfs-root
      containers:
      - name: cvmfs
        image: fbarreir/cvmfs-prp:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/sbin/unmount-and-terminate.sh"]
        env:
        - name: MOUNT_REPOS
          value: "atlas.cern.ch,atlas-condb.cern.ch,atlas-nightlies.cern.ch,grid.cern.ch,sft.cern.ch,sft-nightlies.cern.ch,unpacked.cern.ch"
        resources:
           limits:
             memory: 4Gi
             cpu: 1
           requests:
             memory: 0.5Gi
             cpu: 0.01
        livenessProbe:
          exec:
            command:  # returns 0(=Success) only if there are 7 cvmfs mounts
              - /bin/sh
              - -c
              - "[ `df -h | grep cvmfs2 | wc -l` -eq 7 ]"
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name:  cvmfs-root
          mountPath: /cvmfs
          subPath: cvmfs-k8s
          mountPropagation: Bidirectional
        - name: cvmfs-config
          mountPath: /etc/cvmfs/
      priorityClassName: system-node-critical
      volumes:
      - name: cvmfs-root
        persistentVolumeClaim:
          claimName: cvmfs-root
      - name: cvmfs-config
        configMap:
          name: cvmfs-config

