apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-nodeplugin
  namespace: cvmfs
  labels: 
    k8s-app: cvmfs-nodeplugin
spec:
  selector:
    matchLabels:
      k8s-app: cvmfs-nodeplugin
  template:
    metadata: 
      labels:
        k8s-app: cvmfs-nodeplugin
    spec:
      serviceAccount: cvmfs-nodeplugin
      initContainers:
      - name: create-mountpoint
        image: busybox
        command: ['sh', '-c', "mkdir -p /cvmfs-root/cvmfs-k8s"]
        resources:
           limits:
             memory: 0.5Gi
             cpu: 1
           requests:
             memory: 0.2Gi
             cpu: 0.01
        volumeMounts:
        - mountPath: /cvmfs-root
          name:  cvmfs-root
      containers:
      - name: cvmfs
        image: fbarreir/cvmfs-prp:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/sbin/unmount-and-terminate.sh"]
        env:
        - name: MOUNT_REPOS
          value: "atlas.cern.ch,atlas-condb.cern.ch,atlas-nightlies.cern.ch,grid.cern.ch,sft.cern.ch"
        - name: SQUID_URI
          value: "DIRECT"
        resources:
           limits:
             memory: 4Gi
             cpu: 1
           requests:
             memory: 0.5Gi
             cpu: 0.01
        volumeMounts:
        - mountPath: /cvmfs
          name:  cvmfs-root
          subPath: cvmfs-k8s
          mountPropagation: Bidirectional
      volumes:
      - name: cvmfs-root
        persistentVolumeClaim:
          claimName: cvmfs-root

